spring.application.name=PortailSuiviDoctorat

spring.datasource.url=jdbc:h2:mem:PortailSuiviDoctoratDB
spring.datasource.username=admin
spring.datasource.password=1234
server.port=8080
spring.h2.console.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/portailsuividoctorat
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true